<?php

$this->loadBlock('start', array(
	'title' => 'Add a subscriber'
));

?>

<form>
	
	<div class="well clearfix">
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php echo $this->translate('Public key'); ?><b>*</b></label>
			<div class="col-lg-10">
				<input type="text" name="title" class="form-control" required="required" />
			</div>
		</div>
		
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php echo $this->translate('Private key'); ?><b>*</b></label>
			<div class="col-lg-10">
				<input type="text" name="keywords" class="form-control" required="required" />
			</div>
		</div>
		
	</div>
	
	<button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> <?php echo $this->translate('Save'); ?></button>
	<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-floppy-open"></span> <?php echo $this->translate('Cancel'); ?></button>
	
</form>

<script>
	
	$(function() {
		
		$("form").submit(function(event) {
			event.preventDefault();
			var data = $(this).serialize();
			
			$.ajax({
				url		: "/admin/module/re-captcha/save.ajax",
				data	: data,
				success	: function(response){
					if (response == "1") {
						window.location.reload();
					} else {
						
						alert(response);
					}
				}
			});
		});
		
	});
	
</script>

<?php $this->loadBlock('end'); ?>
