<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<span class="glyphicon glyphicon-list"></span> <?php echo $this->translate('Menu'); ?> <span class="caret"></span>
	  </button> 
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Subscribe:Admin:Subscriber@addAction'); ?>"><i class="glyphicon glyphicon-user"></i> <?php $this->show('Add new subscriber'); ?></a></li>
		 <li><a href="<?php echo $this->url('Subscribe:Admin:Send@indexAction'); ?>"><i class="glyphicon glyphicon-envelope"></i> <?php $this->show('New bulk-sending'); ?></a></li>
		 <li class="divider"></li>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Subscribe:Admin:Browser@saveAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Subscribe:Admin:Browser@deleteSelectedAction'); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
	  </ul>
	</div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Subscribers')); ?>

<form>
	<table class="table table-hover table-bordered table-striped table-condensed">
		<thead>
			<tr>
				<th class="text-center">
                    <?php if (!empty($subscribers)): ?>
                    <input type="checkbox" />
                    <?php endif; ?>
                </th>
				<th class="text-center"><?php $this->show('#'); ?></th>
				<th class="text-center"><?php $this->show('Name'); ?></th>
				<th class="text-center"><?php $this->show('Email'); ?></th>
				<th class="text-center"><?php $this->show('Active'); ?></th>
				<th class="text-center"><?php $this->show('Actions'); ?></th>
			</tr>
		</thead>
		<?php if (!empty($subscribers)): ?>
		<tbody>
			<?php foreach ($subscribers as $subscriber): ?>
			<tr>
				<td class="text-center">
                    <input type="checkbox" name="toDelete[<?php echo $subscriber->getId(); ?>]" />
                </td>
				<td class="text-center text-muted"><?php echo $subscriber->getId(); ?></td>
				<td class="text-center"><?php echo $subscriber->getName(); ?></td>
				<td class="text-center"><?php echo $subscriber->getEmail(); ?></td>
				<td class="text-center">
					<?php echo Element::checkbox(sprintf('active[%s]', $subscriber->getId()), $subscriber->getActive()); ?>
				</td>
				<td class="text-center">
					<a data-button="edit" href="<?php echo $this->url('Subscribe:Admin:Subscriber@editAction', $subscriber->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
					<a data-button="delete" data-url="<?php echo $this->url('Subscribe:Admin:Subscriber@deleteAction', $subscriber->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
		<?php endif; ?>
	</table>

    <?php if (empty($subscribers)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('You have no subscribers'); ?></h2>
    </div>
    <?php endif; ?>
    
</form>

<?php $this->loadPartial('paginator'); ?>
