<?php

use Krystal\Form\Element;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<span class="glyphicon glyphicon-list"></span> <?php echo $this->translate('Menu'); ?> <span class="caret"></span>
	  </button> 
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Subscribe:Admin:Add@indexAction'); ?>"><i class="glyphicon glyphicon-user"></i> <?php $this->show('Add new subscriber'); ?></a></li>
		 <li><a href="<?php echo $this->url('Subscribe:Admin:Send@indexAction'); ?>"><i class="glyphicon glyphicon-envelope"></i> <?php $this->show('New bulk-sending'); ?></a></li>
		 <li class="divider"></li>
		 <li><a href="#" id="save-changes-btn"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" id="remove-selected-btn" data-button="remove-selected"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Subscribers')); ?>

<form>
	<table class="table table-hover table-bordered table-striped table-condensed">
		<thead>
			<tr>
				<th class="text-center"><input type="checkbox" /></th>
				<th class="text-center"><?php $this->show('#'); ?></th>
				<th class="text-center"><?php $this->show('Email'); ?></th>
				<th class="text-center"><?php $this->show('Active'); ?></th>
				<th class="text-center"><?php $this->show('Actions'); ?></th>
			</tr>
		</thead>
		
		<?php if (!empty($pages)): ?>
		
		<tbody>
			<?php foreach ($pages as $page): ?>
			<tr>
				<td class="text-center"><input type="checkbox" name="toDelete[<?php echo $page->id; ?>]" /></td>
				<td class="text-center"><?php echo $page->id; ?></td>
				<td class="text-center"><?php echo $page->title; ?></td>
				<td class="text-center">
					<?php echo Element::radio('default', $page->id, $page->default); ?>
				</td>
				<td class="text-center">
					<a class="view" href="<?php printf('/%s/', $page->slug); ?>"></a>
					<a class="edit" href="<?php printf('/admin/module/pages/edit/%s', $page->id); ?>"></a>
					<a class="delete" href="#" data-id="<?php echo $page->id; ?>"></a>
				</td>
			</tr>
			<?php endforeach; ?>
			
		</tbody>
		<?php endif; ?>
		
	</table>
</form>

<?php $this->loadBlock('paginator'); ?>
