<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>
<form data-group="subscriber">
	<div class="well">
        <?php echo Element::hidden('subscriber[id]', $subscriber->getId()); ?>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('subscriber[name]', $subscriber->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Type person name'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
			<div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('subscriber[email]', $subscriber->getEmail(), array('class' => 'form-control', 'placeholder' => $this->translate('Type their associated email'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
			</div>
		</div>
	</div>

    <?php if ($subscriber->getId()): ?>
	<button class="btn btn-primary" data-button="save" data-url="<?php echo $this->url('Subscribe:Admin:Subscriber@saveAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <?php else: ?>
	<button class="btn btn-primary" data-button="add" data-back-url="<?php echo $this->url('Subscribe:Admin:Subscriber@editAction', null); ?>" data-url="<?php echo $this->url('Subscribe:Admin:Subscriber@saveAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    
    <?php endif; ?>
    
	<button data-button="cancel" data-url="<?php echo $this->url('Subscribe:Admin:Subscriber@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Cancel'); ?></button>

</form>