
<form>
	<div class="well clearfix">
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
				<input type="text" name="name" class="form-control" />
			</div>
		</div>
		
		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
			<div class="col-lg-10">
				<input type="text" name="email" class="form-control" />
			</div>
		</div>
		
	</div>
	
	<button class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> <?php echo $this->translate('Save'); ?></button>
	<button class="btn btn-default"><span class="glyphicon glyphicon-floppy-open"></span> <?php echo $this->translate('Cancel'); ?></button>
	
</form>