<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>
<form data-group="subscriber">
	<div class="well">
        <?php echo Element::hidden('subscriber[id]', $subscriber->getId()); ?>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
			<div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('subscriber[name]', $subscriber->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Type person name'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
			<div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('subscriber[email]', $subscriber->getEmail(), array('class' => 'form-control', 'placeholder' => $this->translate('Type their associated email'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
			</div>
		</div>
	</div>

    <?php $this->loadPartial('actions', array(
        'new' => !$subscriber->getId(),
        'add' => 'Subscribe:Admin:Subscriber@addAction',
        'edit' => 'Subscribe:Admin:Subscriber@editAction',
        'save' => 'Subscribe:Admin:Subscriber@saveAction',
        'cancel' => 'Subscribe:Admin:Subscriber@gridAction'
    )); ?>

</form>