<?php

use Krystal\Form\Element;

defined('KRYSTAL') or die;
?>

<form data-group="subscriber">
	<div class="well">
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Subject'); ?></label>
			<div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('subject', null, array('class' => 'form-control', 'placeholder' => $this->translate('Type the subject'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
			</div>
		</div>
        
		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::textarea('content', null, array('data-wysiwyg' => 'true')); ?>
			</div>
		</div>
    </div>
    
    <button data-button="save" data-url="<?php echo $this->url('Subscribe:Admin:Send@sendAction'); ?>" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i> <?php $this->show('Start'); ?></button>
	<button data-button="cancel" data-url="<?php echo $this->url('Subscribe:Admin:Subscriber@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>