<?php defined('KRYSTAL') or die; ?>

<form>
    <textarea name="content" rows="8" class="form-control"></textarea>

	<button class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="cancel" data-url="<?php echo $this->url('Subscribe:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Cancel'); ?></button>
</form>
