<!DOCTYPE html>
<html>
<head>
    <title><?php $this->show('E-mail confirmation'); ?></title>
    <style>
        body {
          background-color: rebeccapurple;
        }
        
        .container > h2 {
          text-align: center;
          margin-top: 5%;
          color: #fff;
          font-weight: bold;
          font-size: 37px;
        }

    </style>
</head>
<body>

<div class="container">
    <h2>
        <?php if ($success): ?>
        <?php $this->show('Thank you! You have successfully confirmed your email'); ?>

        <?php else: ?>
        <?php $this->show('The confirmation key is invalid'); ?>

        <?php endif; ?>
    </h2>
</div>

</body>
</html>