
<p><?php echo $this->translate('Hello %s!', $name); ?></p>
<p><?php echo $this->translate('You have just subscribed to our news letters on %s. To continue, please confirm your email by clicking on this link', $site); ?>:</p>

<p><a href="<?php echo $link; ?>"><?php echo $link; ?></a></p>

<small><?php echo $this->translate('If you did not request this, then simply ignore this email'); ?></small>

<p><?php $this->show('Thanks!'); ?></p>